spring:
  application:
    name: monitoringApp
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
